name: CI for Pull Requests

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install pytest

      - name: Run tests
        run: pytest

  version-bump:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code again (needed for version bump)
        uses: actions/checkout@v3

      - name: Set Git Identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git config --list  # Log the configuration to confirm it's set correctly

      - name: Checkout master branch
        run: |
          git checkout master  # Ensure we're on the 'master' branch

      - name: Bump Version
        run: |
          pip install bump2version
          bump2version patch  # Change to 'minor' or 'major' if needed
          git config --list  # Log again to ensure Git configuration persists
          git push --follow-tags
