name: CI

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install pytest
          pip install deepsource  # Install DeepSource CLI

      - name: Run tests
        run: |
          pytest --junitxml=pytest-results.xml

      - name: Report test coverage to DeepSource
        uses: deepsourcelabs/test-coverage-action@master
        with:
          key: python
          coverage-file: pytest-results.xml
          dsn: ${{ secrets.DEEPSOURCE_DSN }}


  check-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Fetch at least the last two commits

      - name: Check version bump
        run: |
          if git rev-parse HEAD~1 >/dev/null 2>&1; then
            if git show HEAD:setup.py | grep "version=" | grep -q "$(git show HEAD~1:setup.py | grep "version=")"; then
              echo "Error: Version in setup.py has not been bumped!"
              exit 1
            else
              echo "Version bump detected in setup.py."
            fi
          else
            echo "No previous commit detected; skipping version bump check."
          fi