name: CI

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run tests
        run: |
          pytest --junitxml=pytest-results.xml

      - name: Report test coverage to DeepSource
        uses: deepsourcelabs/test-coverage-action@master
        with:
          key: python
          coverage-file: pytest-results.xml
          dsn: ${{ secrets.DEEPSOURCE_DSN }}

  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Fetch at least the last two commits

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Get current version from setup.py
        id: get_version
        run: |
          # Extract version from setup.py using Python
          version=$(python -c "from setuptools import setup; print(setup().get('version'))")
          echo "Current version: $version"
          echo "version=$version" >> $GITHUB_ENV

      - name: Bump version
        run: |
          # Use semver to bump the version (e.g., bump patch version)
          new_version=$(python -c "import semver; import os; version = os.getenv('version'); new_version = semver.VersionInfo.parse(version).bump_patch(); print(new_version)")
          echo "New version: $new_version"

          # Update version in setup.py
          sed -i "s/version='$version'/version='$new_version'/g" setup.py

          # Commit the version bump
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add setup.py
          git commit -m "Bump version to $new_version"
          git push
